### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by ifredom** [turnerhayes/muziq#1]
Do you have any more details? Unable to start

**Comment by turnerhayes** [comment]
Can you provide more details? Do you get an error when you run `npm start`?

Also, just FYI, it should be noted that this is *very* much a WIP--really more of a sandbox project than anything. Don't use it in any production context.

**Comment by ifredom** [comment]
thank. The reason why it can't start may be that I don't have an environment like MongoDB
